import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";
import { CareerRoleList } from "@/components/career-role-list";

const description = "Explore careers at Priworth and learn about the values, working style, and product mission guiding our team as we build AI meeting intelligence.";
export const metadata: Metadata = contentMetadata({ title: "Careers at Priworth | Build Useful AI for Teams", description, path: "/careers", keywords: ["Priworth careers", "AI startup jobs", "product engineering careers", "meeting intelligence jobs", "work at Priworth"] });
const structuredData = contentSchema({ name: "Careers at Priworth", description, path: "/careers", current: "Careers", type: "WebPage", keywords: ["careers", "AI jobs", "Priworth jobs"], extra: { mainEntity: { "@type": "Organization", name: "Priworth", url: "https://priworth.example" } } });

export default function CareersPage() {
  return <ContentPage eyebrow="Careers" title="Build software that gives teams their context back" intro="Join a focused team working on a practical problem: helping people remember, find, and act on the best parts of their conversations." current="Careers" structuredData={structuredData} beforeSections={<CareerRoleList />} sections={[
    { paragraphs: [<>The best work often starts with a problem that sounds simple and turns out to be deeply human. Meetings create momentum, but their useful context can vanish quickly. At Priworth, we build technology that protects that context and helps teams use it without turning every conversation into paperwork.</>, <>We are looking for people who care about the quality of the experience as much as the ambition of the idea. That includes engineers who think about reliability, designers who make complexity feel calm, product leaders who listen before they prescribe, and customer-minded teammates who can translate real work into useful decisions.</>] },
    { heading: "How we work", paragraphs: [<>We value clear writing, direct communication, and small experiments that teach us something. We prefer a well-understood problem to a crowded roadmap, and we expect decisions to include their reasoning. People are encouraged to ask hard questions early, make their work visible, and change their mind when evidence changes.</>, <>Because Priworth works with sensitive meeting context, responsibility is part of every role. We think about privacy, accessibility, security, and inclusion during discovery rather than treating them as a final review. The product should feel helpful without being intrusive, and our working culture should carry the same respect.</>] },
    { heading: "Room to contribute", paragraphs: [<>A growing company gives people the chance to shape both the product and the way the team operates. You may work across disciplines, talk directly with customers, or own a problem from first question through release. We support that breadth with context, feedback, and a willingness to explain the trade-offs behind a decision.</>, <>We do not measure a career by how busy someone looks. We care about useful outcomes, sustainable pace, and the quality of collaboration that makes difficult work possible. Read more <Link href="/team" className="text-primary underline">about the people behind Priworth</Link>, then <Link href="/contact" className="text-primary underline">contact us</Link> about future opportunities. Current openings will be listed here as they become available.</>] },
  ]} />;
}
