import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BlogListingPage } from "@/components/blog-listing-page";
import { AuthorWidget } from "@/components/blog-components";
import { authors, blogPosts } from "@/lib/blog-posts";

export function generateStaticParams() { return authors.map((author) => ({ author: author.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ author: string }> }): Promise<Metadata> { const { author: slug } = await params; const author = authors.find((item) => item.slug === slug); return author ? { title: `${author.name} | Priworth Blog`, description: `Articles and perspectives by ${author.name}.` } : {}; }
export default async function AuthorPage({ params }: { params: Promise<{ author: string }> }) { const { author: slug } = await params; const author = authors.find((item) => item.slug === slug); if (!author) notFound(); const authorPost = blogPosts.find((post) => post.author.slug === slug)!; const schema = { "@context": "https://schema.org", "@type": "Person", name: author.name, description: author.bio, image: `https://priworth.example${author.avatar}`, url: `https://priworth.example/blog/author/${author.slug}`, sameAs: author.socials ? Object.values(author.socials) : undefined }; return <><BlogListingPage title={`Articles by ${author.name}`} intro={author.bio} posts={blogPosts.filter((post) => post.author.slug === slug)} metadata={{ title: `${author.name} | Priworth Blog` }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="container mx-auto px-6 pb-16"><AuthorWidget post={authorPost} /><div className="mt-4 flex gap-4 text-sm">{author.socials?.linkedin ? <a className="text-primary underline" href={author.socials.linkedin}>LinkedIn</a> : null}{author.socials?.x ? <a className="text-primary underline" href={author.socials.x}>X</a> : null}{author.socials?.website ? <a className="text-primary underline" href={author.socials.website}>Website</a> : null}</div></div></>; }
