import type { Metadata } from "next";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";
import { LegalFaqs } from "@/components/legal-faqs";

const description = "Review the open source licenses, third-party notices, and attribution information that support the Priworth website and product.";
export const metadata: Metadata = contentMetadata({ title: "Licenses and Third-Party Notices | Priworth", description, path: "/licenses", keywords: ["Priworth licenses", "open source notices", "third-party software licenses", "Priworth attribution", "software compliance"] });
const structuredData = contentSchema({ name: "Priworth Licenses and Third-Party Notices", description, path: "/licenses", current: "Licenses", keywords: ["open source licenses", "third-party notices", "software compliance"] });

export default function LicensesPage() {
  return <ContentPage eyebrow="Open source and attribution" title="Licenses that help Priworth move responsibly" intro="Priworth relies on a thoughtful mix of open source software, hosted services, and original product work. This page explains how those pieces are acknowledged and governed." current="Licenses" structuredData={structuredData} sections={[
    { paragraphs: [<>Open source software makes it possible for small teams to build useful products with speed, transparency, and shared craftsmanship. Priworth uses open source libraries for interface components, accessibility behaviors, typography support, data handling, and development tooling. Each dependency is used according to its applicable license, and our goal is to preserve the rights and notices that make that ecosystem possible.</>, <>The software shown on this website may include dependencies distributed under permissive licenses such as MIT, BSD, or Apache-2.0, as well as other notices supplied by their authors. The presence of a dependency does not mean that the original authors endorse Priworth or are responsible for Priworth&apos;s product, service, support, or availability.</>] },
    { heading: "How notices are maintained", paragraphs: [<>Dependency manifests and lockfiles identify the versions used by the application. During normal maintenance, the team reviews updates for security, compatibility, and license changes before they reach a production environment. This process helps us understand what we ship and gives maintainers a clear record when a package is added, removed, or upgraded.</>, <>Some third-party services have their own terms, privacy statements, trademarks, or attribution requirements. Those requirements remain with their respective owners. Product names and logos referenced in the Priworth experience are used to describe integrations or compatibility and do not transfer ownership of those marks.</>] },
    { heading: "Your responsibilities", paragraphs: [<>If you redistribute software that incorporates Priworth code or content, you are responsible for complying with the licenses that apply to the material you use. This page is informational and does not replace the license text shipped with a particular dependency. Where an upstream project requires a notice, the authoritative notice and license should be treated as controlling.</>, <>Questions about an attribution, a dependency, or a notice can be sent through the <a href="/contact" className="text-primary underline">Contact page</a>. We welcome corrections when a notice is incomplete or when a maintainer has updated licensing information. Responsible software stewardship is an ongoing practice, and clear communication is part of keeping it healthy.</>] },
  ]}><LegalFaqs kind="licenses" /></ContentPage>;
}
