import type { Metadata } from "next";
import Image from "next/image";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";

const description = "Meet the Priworth team behind a calmer, clearer approach to AI meeting intelligence, searchable team knowledge, and better collaboration.";
export const metadata: Metadata = contentMetadata({ title: "Meet the Priworth Team | People Behind the Product", description, path: "/team", keywords: ["Priworth team", "Priworth leadership", "AI product team", "meeting intelligence company", "Priworth people"] });
const structuredData = contentSchema({ name: "The Priworth Team", description, path: "/team", current: "Team", type: "AboutPage", keywords: ["Priworth team", "company leadership", "AI product team"], extra: { mainEntity: { "@type": "Organization", name: "Priworth", employee: [{ "@type": "Person", name: "David Park", jobTitle: "Engineering Manager", image: "https://priworth.example/DavidPark.png" }, { "@type": "Person", name: "Monica Kurt", jobTitle: "Product Manager", image: "https://priworth.example/MonicaKurt.png" }] } } });

export default function TeamPage() {
  return <ContentPage eyebrow="The Priworth team" title="People building better memory for modern teams" intro="Priworth brings together product, engineering, research, and customer perspective to make meeting intelligence genuinely useful." current="Team" structuredData={structuredData} beforeSections={<div className="mt-12 grid gap-6 md:grid-cols-2"><div className="rounded-xl border bg-muted/30 p-6"><Image src="/DavidPark.png" alt="David Park" width={96} height={96} className="size-24 rounded-full object-cover" /><h2 className="heading-sm mt-5">David Park</h2><p className="text-primary mt-1 text-sm font-medium">Engineering Manager</p><p className="text-muted-foreground mt-4">David focuses on dependable systems, thoughtful tooling, and the engineering habits that make Priworth feel fast and trustworthy.</p></div><div className="rounded-xl border bg-muted/30 p-6"><Image src="/MonicaKurt.png" alt="Monica Kurt" width={96} height={96} className="size-24 rounded-full object-cover" /><h2 className="heading-sm mt-5">Monica Kurt</h2><p className="text-primary mt-1 text-sm font-medium">Product Manager</p><p className="text-muted-foreground mt-4">Monica connects customer needs to focused product decisions that help teams move from meeting notes to meaningful action.</p></div></div>} sections={[
    { paragraphs: [<>The Priworth team cares about the space between a conversation and what happens next. That space includes decisions, questions, handoffs, and small details that often disappear when a meeting ends. We build tools that help teams keep the valuable parts without adding more work to every calendar invitation.</>, <>Our work combines technical curiosity with respect for how people actually collaborate. We ask whether a feature makes context clearer, whether it gives users enough control, and whether it helps a team act with more confidence. The answers shape our product decisions as much as benchmarks and implementation details do.</>] },
    { heading: "A multidisciplinary way of working", paragraphs: [<>Engineers, designers, product thinkers, and customer advocates work closely at Priworth. Engineering makes the experience fast and dependable. Product turns real workflow problems into focused decisions. Design protects clarity and accessibility. Customer conversations keep us honest about what is useful outside a demo.</>, <>We believe great collaboration does not require everyone to think the same way. It requires a shared standard for listening, testing assumptions, and explaining trade-offs. That standard helps us build a product that can serve a small project team while still making sense for an organization with complex meeting rhythms.</>] },
    { heading: "People and profiles", paragraphs: [<>Our team members are contributors first: people who care about the details that determine whether software earns trust. The profiles below highlight the product and engineering perspective behind Priworth. As the team grows, this page will expand to recognize the people who make the work possible.</>] },
  ]} />;
}
