import type { Metadata } from "next";
import Link from "next/link";
import { LpNavbar1 } from "@/components/pro-blocks/landing-page/lp-navbars/lp-navbar-1";
import { Footer1 } from "@/components/pro-blocks/landing-page/footers/footer-1";
import { BlogCard, BlogHero, CategoryLinks, CompactPost } from "@/components/blog-components";
import { blogCategorySlug, blogPosts, categories } from "@/lib/blog-posts";

export const metadata: Metadata = { title: "Priworth Blog | Ideas for Better Work and Creative Output", description: "Explore practical ideas about productivity, content, tools, creative workflows, and modern team work from the Priworth blog.", keywords: ["Priworth blog", "productivity", "content strategy", "software reviews", "creative workflow"], alternates: { canonical: "/blog" }, openGraph: { title: "Priworth Blog", description: "Practical ideas for better work and creative output.", url: "https://priworth.example/blog", type: "website" } };

export default async function BlogPage({ searchParams }: { searchParams: Promise<{ limit?: string }> }) {
  const params = await searchParams;
  const limit = Math.min(Math.max(Number(params.limit) || 9, 9), blogPosts.length);
  const visible = blogPosts.slice(0, limit);
  return <><LpNavbar1 /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Blog", name: "Priworth Blog", url: "https://priworth.example/blog", blogPost: blogPosts.map((post) => ({ "@type": "BlogPosting", headline: post.title, url: `https://priworth.example/blog/${post.slug}`, datePublished: post.date, author: { "@type": "Person", name: post.author.name } })) }) }} /><section className="bg-background section-padding-y"><div className="container-padding-x container mx-auto flex flex-col gap-12"><header className="mx-auto flex max-w-2xl flex-col items-center gap-5 text-center"><p className="text-primary text-sm font-medium">The Priworth journal</p><h1 className="heading-xl text-foreground">Ideas that make the work clearer</h1><p className="text-muted-foreground text-lg">Practical stories about tools, creative workflows, product thinking, and the systems behind better work.</p></header><BlogHero post={blogPosts[0]} /><CategoryLinks /><section aria-labelledby="latest-heading"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-primary text-sm font-medium">Latest thinking</p><h2 id="latest-heading" className="heading-md">Explore the archive</h2></div><span className="text-muted-foreground text-sm">{blogPosts.length} stories</span></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((post) => <BlogCard key={post.slug} post={post} />)}</div>{limit < blogPosts.length ? <div className="mt-10 flex justify-center"><Link href="/blog?limit=18" className="rounded-full border border-primary px-6 py-3 text-sm font-medium text-primary transition hover:bg-primary hover:text-primary-foreground">Load more posts</Link></div> : null}</section><section className="border-t pt-10" aria-labelledby="compact-heading"><div className="mb-5"><p className="text-primary text-sm font-medium">Quick reads</p><h2 id="compact-heading" className="heading-md">More from the archive</h2></div><div className="grid gap-x-8 md:grid-cols-2 lg:grid-cols-3">{blogPosts.slice().reverse().map((post) => <CompactPost key={`compact-${post.slug}`} post={post} />)}</div></section><aside className="rounded-xl border bg-secondary p-6 text-center"><p className="text-muted-foreground text-sm">Browse by topic</p><div className="mt-4 flex flex-wrap justify-center gap-2">{categories.map((category) => <Link key={category} href={`/blog/category/${encodeURIComponent(category.toLowerCase().replaceAll(" ", "-"))}`} className="text-primary text-sm underline">{category}</Link>)}</div></aside></div></section></main><Footer1 /></>;
}
