import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";

const description = "Read the Priworth privacy policy to understand what information we collect, why we use it, how we protect it, and the choices available to you.";
export const metadata: Metadata = contentMetadata({ title: "Privacy Policy | Priworth", description, path: "/privacy", keywords: ["Priworth privacy policy", "AI meeting privacy", "meeting transcription data", "privacy rights", "data protection"] });
const structuredData = contentSchema({ name: "Priworth Privacy Policy", description, path: "/privacy", current: "Privacy Policy", keywords: ["privacy policy", "data protection", "meeting data"] });

export default function PrivacyPage() {
  return <ContentPage eyebrow="Privacy and trust" title="A clear approach to your information" intro="Priworth is designed to help teams use meeting knowledge responsibly. This policy explains the information we handle and the choices that guide its use." current="Privacy Policy" structuredData={structuredData} sections={[
    { paragraphs: [<>This Privacy Policy describes how Priworth collects, uses, stores, and protects information when you visit our website or use our services. We write it in practical language because privacy choices are meaningful only when people can understand them. By using Priworth, you acknowledge the practices described here and any product-specific notices presented when you connect a service.</>, <>The information we handle depends on how you interact with us. You may provide contact details when you request information, create an account, contact support, or participate in a product conversation. We may also receive technical information such as browser type, device information, approximate location, and pages visited so we can keep the website secure and improve its performance.</>] },
    { heading: "Meeting and account information", paragraphs: [<>When Priworth is configured to process meeting content, the service may handle recordings, transcripts, summaries, participant names, calendar details, action items, and related workspace information. We use that information to provide the features requested by the workspace, maintain security, troubleshoot problems, and improve reliability. Workspace administrators control many settings, including retention and access.</>, <>We do not sell meeting content or use private workspace material for unrelated advertising. Access is limited according to role, technical controls, and operational need. Teams should avoid placing information into a meeting or workspace unless they have a lawful basis and appropriate permission to share it.</>] },
    { heading: "Choices, retention, and rights", paragraphs: [<>You can contact us to ask questions about information associated with you, request correction, or ask about deletion where applicable. Some records may need to be retained for security, legal, billing, or dispute-resolution reasons. When information is no longer needed for an identified purpose, we aim to delete it or securely de-identify it according to our retention practices.</>, <>We may update this policy as the product, legal requirements, or privacy expectations change. The effective date will be updated when material changes are made. For questions about this policy or a privacy request, please use the <Link href="/contact" className="text-primary underline">Contact page</Link>. You can also review our <Link href="/disclaimer" className="text-primary underline">Disclaimer</Link> for information about AI-generated meeting insights.</>] },
  ]} />;
}
