import Link from "next/link";
import { ArrowRight, Clock3, Eye, Star } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { blogCategorySlug, type BlogMedia, type BlogPost } from "@/lib/blog-posts";

export function BlogMedia({ media }: { media: BlogMedia }) {
  if (media.type === "youtube" || media.type === "vimeo") {
    const src = media.type === "youtube" ? `https://www.youtube.com/embed/${media.videoId}` : `https://player.vimeo.com/video/${media.videoId}`;
    return <div className="aspect-video overflow-hidden rounded-xl border bg-black"><iframe className="size-full" src={src} title={media.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>;
  }
  return <div className="overflow-hidden rounded-xl border bg-muted"><iframe className="h-40 w-full" src={media.url} title={media.title} loading="lazy" allow="autoplay" /></div>;
}

function PostMeta({ post, showViews = false }: { post: BlogPost; showViews?: boolean }) { return <div className="text-muted-foreground flex flex-wrap items-center gap-3 text-xs"><time dateTime={post.date}>{post.date}</time><span>•</span><span className="inline-flex items-center gap-1"><Clock3 className="size-3" />{post.readTime}</span>{showViews ? <><span>•</span><span className="inline-flex items-center gap-1"><Eye className="size-3" />{post.views.toLocaleString()}</span></> : null}</div>; }

export function ReviewStars({ rating, maxRating }: { rating: number; maxRating: number }) { return <div className="text-primary flex items-center gap-1" aria-label={`${rating} out of ${maxRating} stars`}>{Array.from({ length: maxRating }, (_, index) => <Star key={index} className={`size-4 ${index < Math.round(rating) ? "fill-current" : ""}`} />)}<span className="text-foreground ml-1 text-sm font-semibold">{rating}/{maxRating}</span></div>; }

export function BlogCard({ post }: { post: BlogPost }) { return <Card className="group overflow-hidden rounded-xl border bg-background py-0 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><Link href={`/blog/${post.slug}`}><div className="relative aspect-video overflow-hidden bg-muted"><img src={post.image} alt={post.imageAlt} className="size-full object-cover transition duration-500 group-hover:scale-105" /></div></Link><CardContent className="flex flex-col gap-3 p-5"><PostMeta post={post} /><h3 className="text-foreground text-lg font-semibold leading-tight"><Link href={`/blog/${post.slug}`} className="hover:text-primary">{post.title}</Link></h3><p className="text-muted-foreground line-clamp-2 text-sm">{post.excerpt}</p><div className="flex items-center justify-between gap-3"><span className="text-primary text-sm font-medium">Read more <ArrowRight className="ml-1 inline size-3.5" /></span>{post.review ? <ReviewStars rating={post.review.rating} maxRating={post.review.maxRating} /> : null}</div></CardContent></Card>; }

export function CompactPost({ post }: { post: BlogPost }) { return <Link href={`/blog/${post.slug}`} className="group flex items-center gap-4 border-b py-4 last:border-b-0"><img src={post.image} alt="" className="size-16 shrink-0 rounded-lg object-cover" /><span className="min-w-0"><span className="text-primary text-xs font-medium">{post.category}</span><span className="text-foreground mt-1 block truncate text-sm font-semibold group-hover:text-primary">{post.title}</span><span className="text-muted-foreground mt-1 block text-xs">{post.date} · {post.readTime}</span></span></Link>; }

export function CategoryLinks({ active }: { active?: string }) { return <nav className="flex flex-wrap justify-center gap-2" aria-label="Blog categories"><Link href="/blog" className={`rounded-full border px-4 py-2 text-sm transition ${!active ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background hover:border-primary hover:text-primary"}`}>All posts</Link>{["Music", "Video", "Reviews", "Content Creation", "Product", "AI Tools"].map((category) => { const slug = blogCategorySlug(category); return <Link key={category} href={`/blog/category/${slug}`} className={`rounded-full border px-4 py-2 text-sm transition ${active === slug ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background hover:border-primary hover:text-primary"}`}>{category}</Link>; })}</nav>; }

export function ShareLinks({ post }: { post: BlogPost }) { const url = `https://priworth.example/blog/${post.slug}`; return <div className="flex flex-wrap gap-2"><span className="text-muted-foreground mr-2 text-sm">Share</span><Button asChild size="sm" variant="outline"><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer">LinkedIn</a></Button><Button asChild size="sm" variant="outline"><a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(post.title)}`} target="_blank" rel="noreferrer">X</a></Button><Button asChild size="sm" variant="outline"><a href={`mailto:?subject=${encodeURIComponent(post.title)}&body=${encodeURIComponent(url)}`}>Email</a></Button></div>; }

export function AuthorWidget({ post }: { post: BlogPost }) { return <div className="flex items-center gap-4 rounded-xl border bg-muted/30 p-5"><img src={post.author.avatar} alt={post.author.name} className="size-14 rounded-full object-cover" /><div><Link href={`/blog/author/${post.author.slug}`} className="text-foreground font-semibold hover:text-primary">{post.author.name}</Link><p className="text-muted-foreground mt-1 text-sm">{post.author.bio}</p></div></div>; }

export function BlogHero({ post }: { post: BlogPost }) { return <section className="overflow-hidden rounded-2xl border bg-secondary"><div className="grid items-stretch lg:grid-cols-[1.1fr_0.9fr]"><div className="flex flex-col justify-center gap-5 p-6 md:p-10"><div className="flex items-center gap-3"><Badge variant="outline">Featured story</Badge><span className="text-muted-foreground inline-flex items-center gap-1 text-xs"><Eye className="size-3" />{post.views.toLocaleString()}</span></div><h2 className="heading-lg text-foreground">{post.title}</h2><PostMeta post={post} /><p className="text-muted-foreground text-base">{post.description}</p><Button asChild className="w-fit"><Link href={`/blog/${post.slug}`}>Read the story <ArrowRight /></Link></Button></div><div className="aspect-video w-full overflow-hidden lg:aspect-auto lg:min-h-full"><img src={post.image} alt={post.imageAlt} className="size-full object-cover" /></div></div></section>; }

export function BlogCtaNewsletter() { return <div className="flex min-w-0 flex-col gap-5"><section className="overflow-hidden rounded-2xl border bg-primary p-5 text-primary-foreground sm:p-6"><div className="flex min-w-0 flex-col items-start gap-4"><span className="rounded-full border border-primary-foreground/30 px-3 py-1 text-xs font-medium">Keep the good ideas moving</span><h2 className="text-2xl font-semibold leading-tight">Bring sharper thinking into your next week.</h2><p className="text-primary-foreground/80 text-sm">Get a short, useful note about better workflows, tools, and team habits.</p><Button asChild variant="secondary" className="w-full"><Link href="/contact">Start a conversation <ArrowRight /></Link></Button></div></section><section className="min-w-0 rounded-xl border bg-background p-5"><p className="text-primary text-sm font-medium">The Priworth newsletter</p><h2 className="text-foreground mt-1 text-lg font-semibold">One thoughtful note, occasionally.</h2><p className="text-muted-foreground mt-2 text-sm">New guides and product thinking, delivered simply.</p><form className="mt-4 flex min-w-0 flex-col gap-2 sm:flex-row" action="/contact"><label className="sr-only" htmlFor="blog-newsletter-email">Email address</label><input id="blog-newsletter-email" name="email" type="email" required placeholder="you@company.com" className="border-input bg-background text-foreground placeholder:text-muted-foreground h-10 min-w-0 w-full rounded-md border px-3 text-sm" /><Button type="submit" className="w-full shrink-0 sm:w-auto">Subscribe</Button></form></section></div>; }
