import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";

const description = "Learn how Priworth membership works, what teams receive at each stage, and how to choose an AI meeting intelligence plan with confidence.";
export const metadata: Metadata = contentMetadata({ title: "Priworth Membership | Plans for Meeting Intelligence", description, path: "/membership", keywords: ["Priworth membership", "AI meeting plans", "meeting notes subscription", "team productivity plans", "Priworth pricing"] });
const structuredData = contentSchema({ name: "Priworth Membership", description, path: "/membership", current: "Membership", keywords: ["membership", "AI meeting plans", "meeting intelligence pricing"], extra: { mainEntity: { "@type": "OfferCatalog", name: "Priworth membership options" } } });

export default function MembershipPage() {
  return <ContentPage eyebrow="Membership" title="A membership that grows with your team" intro="Priworth gives individuals and teams a practical way to capture meeting knowledge, keep work organized, and make better use of every conversation." current="Membership" structuredData={structuredData} sections={[
    { paragraphs: [<>Membership is built around the way teams actually adopt new tools. Some people begin with a few important meetings and expand after they see the value of searchable context. Others need a shared workspace from the first day. Priworth supports both paths with a clear experience that keeps essential meeting intelligence close to the work.</>, <>Every membership is intended to reduce the hidden cost of meetings: repeated explanations, lost decisions, unclear ownership, and time spent recreating notes. The right option depends on how many people need access, how often your team meets, and which integrations matter to your workflow.</>] },
    { heading: "What members receive", paragraphs: [<>Members can use Priworth to capture conversations, review AI-assisted summaries, find decisions, organize topics, and share useful context with teammates. Features may vary by plan, but the product principle remains consistent: information should be easy to understand, easy to revisit, and connected to the action that follows.</>, <>Teams can establish shared habits around meeting preparation, follow-up, and review. A consistent workspace helps new teammates catch up faster and gives project owners a reliable record of what was discussed. Explore the <Link href="/#features" className="text-primary underline">features section</Link> to see the product in context.</>] },
    { heading: "Choosing the right path", paragraphs: [<>Start with the smallest group that can benefit from a shared meeting memory. Define one or two outcomes, such as reducing follow-up time or making customer decisions easier to find, and evaluate the experience against those outcomes. When more teams, meetings, or integrations become important, a broader membership can provide room to grow.</>, <>Membership terms, availability, and pricing can change as Priworth evolves. The current <Link href="/#pricing" className="text-primary underline">pricing section</Link> is the best place to review available options. If your needs are unusual or you need help choosing, <Link href="/contact" className="text-primary underline">contact our team</Link> for a direct conversation rather than guessing at the right fit.</>] },
  ]} />;
}
