import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content-page";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";
import { LegalFaqs } from "@/components/legal-faqs";

const description = "Read the Priworth Terms of Service covering acceptable use, accounts, meeting content, subscriptions, intellectual property, and service responsibilities.";
export const metadata: Metadata = contentMetadata({ title: "Terms of Service | Priworth", description, path: "/terms", keywords: ["Priworth terms of service", "AI meeting software terms", "meeting transcription terms", "acceptable use policy", "Priworth agreement"] });
const structuredData = contentSchema({ name: "Priworth Terms of Service", description, path: "/terms", current: "Terms of Service", keywords: ["terms of service", "acceptable use", "software agreement"] });

export default function TermsPage() {
  return <ContentPage eyebrow="Terms of service" title="The agreement for using Priworth" intro="These terms explain the responsibilities and expectations that apply when you access the Priworth website or use our meeting intelligence services." current="Terms of Service" structuredData={structuredData} sections={[
    { paragraphs: [<>These Terms of Service form an agreement between you or the organization you represent and Priworth. They describe how the service may be accessed, what users are responsible for, and the limits that help us operate a reliable product. If you use Priworth on behalf of an organization, you confirm that you have authority to accept these terms for that organization.</>, <>Product-specific features, pricing, usage limits, and order details may be described in a plan, order form, or other agreement. If a specific written agreement conflicts with these terms, that agreement controls only for the conflicting subject and only to the extent stated.</>] },
    { heading: "Accounts and acceptable use", paragraphs: [<>You are responsible for maintaining accurate account information, protecting credentials, and ensuring that people using your workspace have appropriate permission. You may use Priworth only for lawful purposes and in a way that respects other people&apos;s rights. Do not attempt to bypass access controls, interfere with service operation, test the service in a way that causes harm, or use generated content to mislead others.</>, <>Before recording or processing a meeting, you are responsible for obtaining any notices or permissions required by applicable law and by the expectations of your participants. You should not submit credentials, secrets, or information you are not authorized to process. Review the <Link href="/privacy" className="text-primary underline">Privacy Policy</Link> and <Link href="/disclaimer" className="text-primary underline">Disclaimer</Link> for additional context.</>] },
    { heading: "Content, service, and intellectual property", paragraphs: [<>You retain rights to content you submit, subject to the permissions needed for Priworth to provide, secure, and improve the service as described in applicable notices. Priworth and its licensors retain rights in the service, software, design, documentation, trademarks, and original materials. Feedback may be used to improve the product without creating an obligation to you.</>, <>The service is provided with reasonable care, but no software can promise uninterrupted availability or perfectly accurate automated output. Priworth may change, suspend, or discontinue a feature when necessary for security, legal compliance, or product development. We will communicate material changes where reasonably practical.</>] },
    { heading: "Questions and updates", paragraphs: [<>These terms may be updated as Priworth grows or legal requirements change. The date shown on the current version indicates when it was last revised. Continued use after an update means you accept the revised terms to the extent permitted by law. If you have a question about this agreement, please use the <Link href="/contact" className="text-primary underline">Contact page</Link>.</>, <>Nothing in these terms excludes rights or remedies that cannot legally be excluded. If a provision is found unenforceable, the remaining provisions continue to apply. We want the agreement to be understandable, and we welcome questions where a responsibility or limitation needs clearer explanation.</>] },
  ]}><LegalFaqs kind="terms" /></ContentPage>;
}
