export const careerRoles = {
  "software-engineer": { title: "Senior Software Developer", shortTitle: "Software Engineer", location: "Remote", type: "Full-time", summary: "Build reliable product experiences that help teams capture, search, and act on meeting knowledge.", description: "As a Senior Software Developer at Priworth, you will shape product features from discovery through production. You will work across React, Next.js, TypeScript, APIs, and data flows while partnering with design and product to turn ambiguous workflow problems into clear, dependable experiences.", responsibilities: ["Design and ship accessible web experiences", "Improve performance and reliability across product surfaces", "Review code and help establish pragmatic engineering standards", "Collaborate with product and customer-facing teammates"], requirements: ["Strong TypeScript and modern React experience", "Experience shipping production web applications", "Clear written communication and thoughtful technical judgment"] },
  "devops-engineer": { title: "DevOps Engineer", shortTitle: "DevOps", location: "Remote", type: "Full-time", summary: "Create the delivery, observability, and infrastructure foundations for a dependable AI product.", description: "The DevOps Engineer will make it easier for Priworth teams to ship safely and understand the systems they operate. You will improve CI/CD, cloud infrastructure, monitoring, incident readiness, and developer tooling while keeping security and cost visible in everyday decisions.", responsibilities: ["Own and improve deployment pipelines", "Build observability and operational feedback loops", "Automate repeatable infrastructure and environment tasks", "Partner with engineering on resilience and security"], requirements: ["Experience with cloud infrastructure and CI/CD", "Comfortable with scripting, containers, and monitoring", "Calm, structured approach to operational problems"] },
  "qa-engineer": { title: "QA Engineer", shortTitle: "Quality Assurance", location: "Remote", type: "Full-time", summary: "Help teams trust every release through thoughtful testing, automation, and product feedback.", description: "As a QA Engineer, you will build confidence into the product development cycle. You will explore workflows, automate high-value regression coverage, and work closely with engineers and product partners to make quality visible early rather than at the end of a release.", responsibilities: ["Create risk-based test plans for new workflows", "Build and maintain automated regression coverage", "Investigate defects and communicate reproduction clearly", "Advocate for accessibility and reliable user experiences"], requirements: ["Hands-on web application testing experience", "Understanding of automated testing practices", "Curiosity and strong attention to user impact"] },
  "data-engineer": { title: "Data Engineer", shortTitle: "Data Engineering", location: "Remote", type: "Full-time", summary: "Build trustworthy data foundations for meeting insights and product decisions.", description: "The Data Engineer will help Priworth move reliable information through the systems that power search, analytics, and product learning. You will design maintainable pipelines, improve data quality, and collaborate with engineering and product on responsible use of meeting intelligence data.", responsibilities: ["Design dependable ingestion and transformation workflows", "Improve data quality, lineage, and observability", "Partner on analytics and product measurement", "Document systems and make operational ownership clear"], requirements: ["Experience building production data pipelines", "Strong SQL and data modeling fundamentals", "Careful approach to privacy, quality, and access"] },
  "seo-specialist": { title: "SEO Specialist", shortTitle: "SEO", location: "Remote", type: "Full-time", summary: "Help people discover useful, trustworthy information about meeting intelligence.", description: "As an SEO Specialist, you will connect search intent to clear product education. You will work across technical SEO, content strategy, structured data, internal linking, and measurement to grow Priworth&apos;s visibility without sacrificing usefulness or trust.", responsibilities: ["Build and prioritize technical SEO improvements", "Develop search-led content briefs and internal linking plans", "Measure organic performance and communicate insights", "Partner with product and content on structured, accessible pages"], requirements: ["Experience with technical and content SEO", "Comfort with analytics, Search Console, and structured data", "Strong editorial judgment and understanding of user intent"] },
} as const;

export type CareerRoleSlug = keyof typeof careerRoles;
export type CareerRole = (typeof careerRoles)[CareerRoleSlug];
