import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content-page";
import { StandalonePricing } from "@/components/standalone-pricing";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";

const description = "Compare Priworth plans for AI meeting notes, transcription, search, integrations, and team insights.";
export const metadata: Metadata = contentMetadata({ title: "Priworth Pricing | Simple Meeting Intelligence Plans", description, path: "/pricing", keywords: ["Priworth pricing", "AI meeting notes pricing", "meeting transcription plans", "team productivity pricing"] });
const structuredData = contentSchema({ name: "Priworth Pricing", description, path: "/pricing", current: "Pricing", keywords: ["pricing", "AI meeting plans", "meeting intelligence"], extra: { mainEntity: { "@type": "OfferCatalog", name: "Priworth plans", itemListElement: [{ "@type": "Offer", name: "Free", price: "0", priceCurrency: "USD" }, { "@type": "Offer", name: "Pro", price: "15", priceCurrency: "USD" }] } } });

export default function PricingPage() { return <ContentPage eyebrow="Pricing" title="A clear plan for every stage of team collaboration" intro="Start simply, understand the value, and expand when your team needs more meeting history, integrations, and support." current="Pricing" structuredData={structuredData} beforeSections={<StandalonePricing />} sections={[{ paragraphs: [<>Priworth pricing is designed around the practical value of making conversations easier to capture, revisit, and act on. The Free plan gives individuals and small teams a focused way to explore meeting notes, basic transcription, and a short history. It is useful when you are learning which meetings benefit most from a shared record.</>, <>The Pro plan is built for teams that want meeting intelligence to become part of their regular workflow. Unlimited meetings, advanced transcription, integrations, searchable history, and priority support help teams spend less time reconstructing context and more time making progress.</>] }, { heading: "Choosing the right plan", paragraphs: [<>Begin with a clear outcome: reduce follow-up work, help absent teammates catch up, or make decisions easier to find. Use that outcome to evaluate the experience with a real set of meetings. As the number of users, integrations, and retained conversations grows, a broader plan can provide the consistency and capacity your team needs.</>, <>Plans may change as Priworth develops. The current cards above show the available options, while the <Link href="/faq" className="text-primary underline">FAQ</Link> answers common questions about meeting capture, privacy, and billing. For a specific team requirement, <Link href="/contact" className="text-primary underline">contact us</Link> and share the workflow you are evaluating.</>] }, { heading: "Built around useful work", paragraphs: [<>A plan is valuable when it supports a habit people can keep. Priworth helps teams prepare with context, preserve decisions, and make ownership visible after a meeting. That means the product should feel clear for a first-time user while remaining useful for a team that has accumulated months of shared knowledge.</>, <>We aim to make pricing understandable, the product experience calm, and the path from evaluation to adoption direct. You can see what each plan is intended to support, start with the level that fits your current needs, and revisit the decision as the work changes.</>] }]} />; }
