import type { Metadata } from "next";
import { ContentPage } from "@/components/content-page";
import { StandaloneFaq, questions } from "@/components/standalone-faq";
import { contentMetadata, contentSchema } from "@/lib/content-page-seo";

const description = "Find answers about Priworth meeting capture, transcription, summaries, privacy, billing, and integrations.";
export const metadata: Metadata = contentMetadata({ title: "Priworth FAQ | Meeting Intelligence Questions Answered", description, path: "/faq", keywords: ["Priworth FAQ", "AI meeting assistant questions", "meeting transcription FAQ", "Priworth billing", "meeting privacy"] });
const structuredData = contentSchema({ name: "Priworth Frequently Asked Questions", description, path: "/faq", current: "FAQ", type: "WebPage", keywords: ["FAQ", "meeting intelligence questions", "AI meeting assistant"], extra: { mainEntity: { "@type": "FAQPage", mainEntity: questions.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) } } });

export default function FaqPage() { return <ContentPage eyebrow="FAQ" title="Answers that make getting started easier" intro="Find practical answers about meeting capture, accuracy, privacy, integrations, and plans before bringing Priworth into your workflow." current="FAQ" structuredData={structuredData} beforeSections={<StandaloneFaq />} sections={[{ paragraphs: [<>Choosing a meeting intelligence tool is a workflow decision, not just a feature decision. Teams need to understand how capture works, what people can review, how long information remains available, and who controls access. This page is designed to answer those questions in plain language so you can evaluate Priworth with the right expectations.</>, <>The answers below cover the most common starting points. Your workspace configuration, plan, meeting platform, and local requirements may affect the details. If your situation is unusual, the <a href="/contact" className="text-primary underline">Contact page</a> is the fastest way to discuss it with the Priworth team.</>] }, { heading: "A thoughtful way to evaluate Priworth", paragraphs: [<>Start with a small set of meetings where the outcome is easy to see. Review the generated notes, correct anything that needs context, and ask whether the shared record makes the next step clearer. Good adoption comes from a workflow people trust, not from asking everyone to change everything at once.</>, <>You can also explore the <a href="/#features" className="text-primary underline">product features</a>, compare plans on the <a href="/pricing" className="text-primary underline">Pricing page</a>, and review the <a href="/privacy" className="text-primary underline">Privacy Policy</a> before connecting a workspace. Priworth is built to support human judgment, so review and accountability remain part of the experience.</>] }]} />; }
